exeCutable: main.o Courses.o Course.o Student.o Students.o Enrollment.o Enrollments.o
    g++ -o executable main.o Courses.o Course.o Student.o Students.o Enrollment.o Enrollments.o
Courses.o: Courses.h Courses.cpp
    g++ -c Courses.h Courses.cpp
Course.o: Course.h Course.cpp
    g++ -c Course.h Course.cpp
Student.o: Student.h Student.cpp
    g++ -c Student.h Student.cpp
Students.o: Students.h Students.cpp
    g++ -c Students.h Students.cpp
Enrollment.o: Enrollment.h Enrollment.cpp
    g++ -c Enrollment.h Enrollment.cpp
Enrollments.o: Enrollments.h Enrollments.cpp
    g++ -c Enrollments.h Enrollments.cpp
